dist: trusty
sudo: required
group: deprecated-2017Q4
language: python
python: 2.7

cache:
  yarn: true
  directories:
    - "${HOME}/virtualenv/python$(python -c 'import platform; print(platform.python_version())')"
    - "$NODE_DIR"
    - node_modules
    - "${HOME}/google-cloud-sdk"

# Limit builds to master and develop. Note that pull requests to these will still trigger builds
branches:
  only:
    - "master"
    - "develop"

addons:
  apt:
    update: true
    packages:
      - libxmlsec1-dev
  chrome: stable

env:
  global:
    - NODE_ENV=development
    - PIP_DISABLE_PIP_VERSION_CHECK=on
    - SENTRY_LIGHT_BUILD=1
    - SENTRY_SKIP_BACKEND_VALIDATION=1
    # node's version is pinned by .nvmrc and is autodetected by `nvm install`.
    - NODE_DIR="${HOME}/.nvm/versions/node/v$(< .nvmrc)"
    - YARN_VERSION="1.3.2"
script:
  - make travis-lint-$TEST_SUITE
  - make travis-test-$TEST_SUITE
  - make travis-scan-$TEST_SUITE
  # installing dependencies for after_* steps here ensures they get cached
  # since those steps execute after travis runs `store build cache`
  - pip install codecov

after_success:
  - codecov -e TEST_SUITE

after_failure:
  - dmesg | tail -n 100

# each job in the matrix inherits `env/global` and uses everything above,
# but custom `services`, `before_install`, `install`, and `before_script` directives
# may be defined to define and setup individual job environments with more precision.
matrix:
  fast_finish: true
  include:
    # only the sqlite suite runs riak tests
    - python: 2.7
      env: TEST_SUITE=sqlite DB=sqlite
      services:
        - memcached
        - riak
        - redis-server
      install:
        - python setup.py install_egg_info
        - pip install -e ".[dev,tests,optional]"

    - python: 2.7
      env: TEST_SUITE=postgres DB=postgres
      services:
        - memcached
        - redis-server
        - postgresql
      install:
        - python setup.py install_egg_info
        - pip install -e ".[dev,tests,optional]"
      before_script:
        - psql -c 'create database clims;' -U postgres

    - python: 2.7
      env: TEST_SUITE=acceptance
      services:
        - memcached
        - redis-server
        - postgresql
      before_install:
        - find "$NODE_DIR" -type d -empty -delete
        - nvm install
        - npm install -g "yarn@${YARN_VERSION}"
        - docker run -d --network host --name clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:18.14.9
        - docker run -d --network host --name snuba --env SNUBA_SETTINGS=test --env CLICKHOUSE_SERVER=localhost:9000 getsentry/snuba
        - docker ps -a
      install:
        - yarn install --pure-lockfile
        - python setup.py install_egg_info
        - pip install -e ".[dev,tests,optional]"
        - ./bin/install-chromedriver
      before_script:
        - psql -c 'create database clims;' -U postgres

    - python: 2.7
      env: TEST_SUITE=js
      before_install:
        - find "$NODE_DIR" -type d -empty -delete
        - nvm install
        - npm install -g "yarn@${YARN_VERSION}"
      install:
        - yarn install --pure-lockfile

    - python: 2.7
      env: TEST_SUITE=cli
      services:
        - postgresql
        - redis-server
      install:
        - python setup.py install_egg_info
        - pip install -e .
      before_script:
        - psql -c 'create database clims;' -U postgres

    - python: 2.7
      env: TEST_SUITE=dist
      before_install:
        - find "$NODE_DIR" -type d -empty -delete
        - nvm install
        - npm install -g "yarn@${YARN_VERSION}"

    # django 1.8 compatibility
    - python: 2.7
      env: TEST_SUITE=postgres DJANGO_VERSION=">=1.8,<1.9"
      services:
        - memcached
        - redis-server
        - postgresql
      install:
        - python setup.py install_egg_info
        - pip install -e ".[dev,tests,optional]"
      before_script:
        - psql -c 'create database clims;' -U postgres

    # Deploy 'storybook' (component & style guide) - allowed to fail
    - language: node_js
      env: STORYBOOK_BUILD=1
      before_install:
        # Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
        - openssl aes-256-cbc -K $encrypted_020be61ef175_key -iv $encrypted_020be61ef175_iv -in .travis/storybook-credentials.tar.gz.enc -out credentials.tar.gz -d
        # If the SDK is not already cached, download it and unpack it
        - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
        - tar -xzf credentials.tar.gz
        # Use the decrypted service account credentials to authenticate the command line tool
        - gcloud auth activate-service-account --key-file client-secret.json
        - npm install -g "yarn@${YARN_VERSION}"
      install:
        - yarn install --pure-lockfile
        - gcloud version
      script: bash .travis/deploy-storybook.sh
      after_success: skip
      after_failure: skip

  # jobs are defined in matrix/include
  # to specify which jobs are allowed to fail, match the env exactly in matrix/allow_failures
  allow_failures:
    - language: node_js
      env: STORYBOOK_BUILD=1

    - language: python
      env:
        - TEST_SUITE=postgres DB=postgres
        - SENTRY_USE_RUST_NORMALIZER=true
