# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-11 06:55


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.citext
import sentry.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0004_auto_20190814_0840'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', sentry.models.user.UserManager(cache_fields=[b'pk'])),
            ],
        ),
        migrations.AlterField(
            model_name='authprovider',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentry.Organization'),
        ),
        migrations.AlterField(
            model_name='commitauthor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='counter',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentry.Project'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=sentry.db.models.fields.citext.CIEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='groupassignee',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_set1', to='sentry.Group'),
        ),
        migrations.AlterField(
            model_name='groupemailthread',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='groupresolution',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentry.Group'),
        ),
        migrations.AlterField(
            model_name='groupshare',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentry.Group'),
        ),
        migrations.AlterField(
            model_name='groupsnooze',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentry.Group'),
        ),
        migrations.AlterField(
            model_name='lostpasswordhash',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationavatar',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentry.File'),
        ),
        migrations.AlterField(
            model_name='organizationavatar',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='sentry.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='projectavatar',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentry.File'),
        ),
        migrations.AlterField(
            model_name='projectavatar',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='sentry.Project'),
        ),
        migrations.AlterField(
            model_name='projectownership',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentry.Project'),
        ),
        migrations.AlterField(
            model_name='sentryappavatar',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentry.File'),
        ),
        migrations.AlterField(
            model_name='sentryappavatar',
            name='sentry_app',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='sentry.SentryApp'),
        ),
        migrations.AlterField(
            model_name='teamavatar',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentry.File'),
        ),
        migrations.AlterField(
            model_name='teamavatar',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='sentry.Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sentry.File'),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
