# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-14 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('name', 'organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='substance',
            unique_together=set([('name', 'organization')]),
        ),
    ]
