# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0002_auto_20191014_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='current',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='previous',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='clims.Container'),
        ),
    ]
