# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-23 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0004_auto_20191022_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstanceLocation',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('container_version', models.IntegerField(default=1)),
                ('substance_version', models.IntegerField(default=1)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('current', models.BooleanField()),
                ('container', sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substance_locations', to='clims.Container')),
            ],
            options={
                'db_table': 'clims_substancelocation',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='container',
        ),
        migrations.RemoveField(
            model_name='location',
            name='previous',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='target_location',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='work_batch',
        ),
        migrations.RemoveField(
            model_name='substance',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
