# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-23 07:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0005_auto_20191023_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='substancelocation',
            name='substance',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clims.Substance'),
        ),
    ]
