# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-11 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0005_camundaprocess_camundatask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbatchassignee',
            name='work_batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_set', to='clims.WorkBatch'),
        ),
    ]
