# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-23 07:42


from django.db import migrations
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0006_substancelocation_substance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substancelocation',
            name='substance',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='clims.Substance'),
        ),
    ]
