# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-12 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0006_auto_20190911_0655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityinstance',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='activityinstance',
            name='work_batch',
        ),
        migrations.DeleteModel(
            name='ActivityInstance',
        ),
    ]
