# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-23 13:24


from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0005_auto_20190911_0655'),
        ('clims', '0007_auto_20191023_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('extensible_type', sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clims.ExtensibleType')),
                ('organization', sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_organization', to='sentry.Organization')),
            ],
            options={
                'db_table': 'clims_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('previous_name', models.TextField(null=True)),
                ('version', models.IntegerField(default=1)),
                ('latest', models.BooleanField(default=True)),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clims.Project')),
                ('properties', models.ManyToManyField(to='clims.ExtensibleProperty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='substance',
            name='organization',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substance_organization', to='sentry.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'organization')]),
        ),
    ]
