# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.bounded


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0005_auto_20190911_0655'),
        ('clims', '0007_auto_20190912_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginRegistration',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentry.Organization')),
            ],
            options={
                'db_table': 'clims_pluginregistration',
            },
        ),
    ]
