# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-24 14:43
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0008_auto_20191023_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sentry.Organization'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='organization',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substances', to='sentry.Organization'),
        ),
        migrations.AlterField(
            model_name='substance',
            name='project',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clims.Project'),
        ),
    ]
