# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-11-05 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import sentry.db.models.fields.bounded


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0009_auto_20191024_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('document', models.TextField()),
                ('tracking_info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
