# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-18 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0005_auto_20190911_0655'),
        ('clims', '0009_auto_20190916_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensibleProperty',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('latest', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clims_extensibleproperty',
            },
        ),
        migrations.CreateModel(
            name='ExtensiblePropertyType',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('display_name', models.TextField(null=True)),
                ('raw_type', models.TextField(choices=[(b's', b'string'), (b'j', b'json'), (b'i', b'int'), (b'f', b'float'), (b'b', b'bool')])),
            ],
            options={
                'db_table': 'clims_extensiblepropertytype',
            },
        ),
        migrations.CreateModel(
            name='ExtensiblePropertyValue',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('float_value', models.FloatField(null=True)),
                ('int_value', models.IntegerField(null=True)),
                ('string_value', models.TextField(null=True)),
                ('bool_value', models.NullBooleanField()),
            ],
            options={
                'db_table': 'clims_extensiblepropertyvalue',
            },
        ),
        migrations.CreateModel(
            name='ExtensibleType',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('category', models.TextField()),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clims.PluginRegistration')),
            ],
            options={
                'db_table': 'clims_extensibletype',
            },
        ),
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('depth', models.IntegerField(default=1)),
                ('extensible_type', sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clims.ExtensibleType')),
                ('organization', sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentry.Organization')),
                ('origins', models.ManyToManyField(to='clims.Substance')),
                ('parents', models.ManyToManyField(related_name='_substance_parents_+', to='clims.Substance')),
                ('project', sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentry.Project')),
                ('properties', models.ManyToManyField(to='clims.ExtensibleProperty')),
            ],
            options={
                'db_table': 'clims_substance',
            },
        ),
        migrations.AddField(
            model_name='extensiblepropertytype',
            name='extensible_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_types', to='clims.ExtensibleType'),
        ),
        migrations.AddField(
            model_name='extensibleproperty',
            name='extensible_property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clims.ExtensiblePropertyType'),
        ),
        migrations.AddField(
            model_name='extensibleproperty',
            name='extensible_property_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clims.ExtensiblePropertyValue'),
        ),
        migrations.AlterUniqueTogether(
            name='substance',
            unique_together=set([('name', 'organization', 'extensible_type')]),
        ),
    ]
