# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-19 07:07
from __future__ import unicode_literals

import clims.models.file
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0005_auto_20190911_0655'),
        ('clims', '0010_auto_20190918_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationFile',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(
                    primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('file', sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sentry.File')),
                ('organization', sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='sentry.Organization')),
            ],
            options={
                'db_table': 'clims_organizationfile',
            },
            bases=(clims.models.file.StructuredFileMixin, models.Model),
        ),
        migrations.AlterIndexTogether(
            name='organizationfile',
            index_together=set([('name',)]),
        ),
    ]
