# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-09-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0011_auto_20190919_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbatch',
            name='plugin',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='clims.PluginRegistration'),
        ),
    ]
