# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sentry.db.models.fields.bounded
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0012_auto_20190923_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('z', models.IntegerField(default=0)),
                ('container', sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clims.Container')),
            ],
            options={
                'db_table': 'clims_location',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', sentry.db.models.fields.bounded.BoundedBigAutoField(primary_key=True, serialize=False)),
                ('performed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name=b'created')),
                ('source_location', sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transitions', to='clims.Location')),
                ('target_location', sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_transitions', to='clims.Location')),
                ('work_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clims.WorkBatch')),
            ],
            options={
                'db_table': 'clims_transition',
            },
        ),
    ]
