# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-04 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0014_auto_20191007_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='substance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1900, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='substance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(1900, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
