# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0015_auto_20200731_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_work_unit_id', models.TextField(null=True, unique=True)),
                ('external_workflow_instance_id', models.TextField(null=True)),
                ('workflow_provider', models.TextField(null=True)),
                ('work_type', models.TextField(null=True)),
                ('container', sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clims.Container')),
                ('substance', sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clims.Substance')),
                ('work_batch', sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_units', to='clims.WorkBatch')),
            ],
            options={
                'db_table': 'clims_workunit',
            },
        ),
    ]
