# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-21 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0015_auto_20200731_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbatchfile',
            name='file_handle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workbatchfile',
            name='work_batch',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='clims.WorkBatch'),
        ),
    ]
