# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-09-29 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0016_auto_20200921_1231'),
        ('clims', '0017_container_work_batch'),
    ]

    operations = [
    ]
