# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-10-28 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0018_merge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StepVersion',
            new_name='WorkBatchVersion',
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='step',
            name='extensible_type',
        ),
        migrations.RemoveField(
            model_name='step',
            name='organization',
        ),
        migrations.AddField(
            model_name='workbatch',
            name='extensible_type',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clims.ExtensibleType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workbatchversion',
            name='archetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clims.WorkBatch'),
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
