# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-10 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import sentry.db.models.fields.foreignkey


class Migration(migrations.Migration):

    dependencies = [
        ('clims', '0020_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='user',
            field=sentry.db.models.fields.foreignkey.FlexibleForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
