version: "3"
services:
  elasticsearch:
    container_name: clims_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  esdata1:
    driver: local
