name: Common LIMS

on: [push, pull_request]

# TODO: codecov from travis file not yet ported, consider running it via `make test-...`
# TODO: Add acceptance tests (see the old travis file for reference)

jobs:
  server-integrationtests:
    # Python tests that require the entire stack (integration). Note that currently these
    # are all the tests for simplicity, but pure unit tests should be moved to
    # another job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
    - name: Install apt packages
      run: |
          sudo apt-get update
          sudo apt-get install libxmlsec1-dev
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup clims
      run: make install-clims-dev
    - name: Install python packages for toolchain
      run: ./scripts/build-python-reqs
    - name: setup middleware
      run: |
          scripts/build-install-docker
          make middleware
